const FreeSection = [
  "Free Breakfast",
  "Free Airport Transfers",
  "Free City Maps",
  "Free City Tour",
  "Free Internet Access",
  "Free Parking",
  "Free WiFi",
  "Linen Included",
  "Towels Included",
];

const ServiceSection = [
  "24 Hour Reception",
  "24 Hour Security",
  "Airport Transfers",
  "ATM",
  "t-CRCHE",
  "Security Locker",
  "Common Room",
  "Beauty Salon",
  "Bicycle Hire",
  "Business Centre",
  "Concierge",
  "Crèche",
  "Security Lockers",
  "Currency Exchange",
  "Direct Dial Telephone",
  "Express Check-In / Out",
  "Telephone/Fax Facilities",
  "Housekeeping",
  "Internet Access",
  "Internet Café",
  "Late Check-Out",
  "Jobs Board",
  "Laundry Facilities",
  "Luggage Storage",
  "Micowave",
  "Postal Services",
  "Reception (Limited Hours)",
  "Room Service (24 Hours)",
  "Room Service (Limited Hours)",
  "Airport Shuttle Bus",
  "Tours/Travel Desk",
  "Towels For Hire",
  "Wake-Up Calls",
  "Spa & Wellness Center",
  "COVID-19 Safe",
];

const EntertainmentSection = [
  "DVDs",
  "Nightclub",
  "Pool Table",
  "WiFi",
  "Foos ball",
  "Board games",
  "Games Room",
  "Play Station",
];

const GeneralSection = [
  "Adaptors",
  "Air Conditioning",
  "BBQ",
  "Bicycle Parking",
  "Book Exchange",
  "Breakfast Not Included",
  "Cable TV",
  "Card Phones",
  "Ceiling Fan",
  "Children's Play Area",
  "Cots Available",
  "Dishwasher",
  "Dry Cleaning",
  "Dryer",
  "Elevator",
  "Flexible NRR",
  "Fridge/Freezer",
  "Golf Course",
  "Fitness Centre",
  "Self Catering",
  "Cooker",
  "Washing Machine",
  "Card Phones",
  "Utensils",
  "Hair Dryers",
  "Hair Dryers For Hire",
  "Hot Showers",
  "Hot Tub",
  "Indoor Swimming Pool",
  "Iron / Ironing Board",
  "Key Card Access",
  "Linen Not Included",
  "Security Lockers",
  "Meeting Rooms",
  "Outdoor Swimming Pool",
  "Outdoor Terrace",
  "Parking",
  "Reading Light",
  "Safe Deposit Box",
  "Follows Covid-19 Sanitation Guidance",
  "Sauna",
  "Steam Room",
  "Swimming Pool",
  "Tennis Court(S)",
  "Towels Not Included",
  "UKRAINEREFUGEES",
  "Wheelchair Friendly",
];

const FoodAndDrinks = [
  "Bar",
  "Café",
  "Meals Available",
  "Mini-Bar",
  "Mini Supermarket",
  "Restaurant",
  "Tea & Coffee Making Facilities",
  "Vending Machines",
  "t_CAF",
];

export {
  FreeSection,
  ServiceSection,
  EntertainmentSection,
  GeneralSection,
  FoodAndDrinks,
};
