const NameOfCountries: any[] = [
  "Argentina",
  "Australia",
  "Bangladesh",
  "Brazil",
  "Canada",
  "China",
  "Egypt",
  "France",
  "Germany",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Italy",
  "Japan",
  "Jordan",
  "Kenya",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "Nigeria",
  "Pakistan",
  "Palestine",
  "Peru",
  "Philippines",
  "Poland",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "UAE",
  "UK",
  "USA",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
const NameOfCities: any = {
  Argentina: [
    "Buenos Aires",
    "Cordoba",
    "Rosario",
    "Mendoza",
    "Tucuman",
    "La Plata",
  ],
  Australia: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
  ],
  Bangladesh: [
    "Dhaka",
    "Chittagong",
    "Khulna",
    "Rajshahi",
    "Sylhet",
    "Barisal",
  ],
  Brazil: [
    "Sao Paulo",
    "Rio de Janeiro",
    "Brasilia",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
  ],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton"],
  China: [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Hangzhou",
  ],
  Egypt: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Sharm El Sheikh"],
  France: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes"],
  Germany: ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt", "Stuttgart"],
  India: [
    "Delhi",
    "Mumbai",
    "Kolkata",
    "Chennai",
    "Srinagar",
    "Manali",
    "Bengaluru",
    "Hyderabad",
    "Bir",
    "Pune",
    "Jaipur",
    "Lucknow",
    "Ahmedabad",
    "Jibhi",
    "Surat",
    "Kanpur",
    "Nagpur",
    "Sethan",
    "Mcleodganj",
    "Indore",
    "Thane",
    "Bhopal",
    "Jaipur",
    "Goa",
    "Shimla",
    "Agra",
    "Manali",
    "Darjeeling",
    "Kolkata",
    "Amritsar",
    "Ooty",
    "Pondicherry",
    "Kasol",
    "Udaipur",
    "Nanital",
    "Rishikesh",
    "Lonavala",
    "Varanasi",
    "Jaisalmer",
    "Dehradun",
    "Cochin",
    "Coorg",
    "Leh",
    "Madurai",
    "Jodhpur",
    "Dalhousie",
    "Gangtok",
    "Hampi",
    "Mussoorie",
    "Chandigarh",
    "Lucknow",
    "Mysore",
    "Aurangabad",
    "Almora",
    "Gokarna",
    "Haridwar",
    "Kanyakumari",
    "Bodhgaya",
    "Munnar",
    "Varkala",
    "Khajuraho",
    "Pushkar",
    "Wayanad",
    "Srinagar",
  ],
  Indonesia: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
    "Makassar",
  ],
  Iran: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz", "Shiraz"],
  Iraq: ["Baghdad", "Basra", "Mosul", "Erbil", "Kirkuk", "Najaf"],
  Italy: ["Rome", "Milan", "Naples", "Turin", "Florence", "Venice"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Hiroshima", "Sapporo", "Nagoya"],
  Jordan: ["Amman", "Zarqa", "Irbid", "Aqaba", "Salt", "Madaba"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika"],
  Malaysia: [
    "Kuala Lumpur",
    "Penang",
    "Johor Bahru",
    "Ipoh",
    "Kuching",
    "Kota Kinabalu",
  ],
  Mexico: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "Merida",
  ],
  Morocco: ["Casablanca", "Rabat", "Fez", "Marrakech", "Agadir", "Tangier"],
  Netherlands: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
  ],
  Nigeria: ["Lagos", "Abuja", "Kano", "Ibadan", "Benin City", "Port Harcourt"],
  Pakistan: [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Rawalpindi",
    "Faisalabad",
    "Multan",
  ],
  Palestine: [
    "Jerusalem",
    "Gaza City",
    "Tel Aviv (Old name: Tel Aviv-Yafo)",
    "Ramallah",
    "Bethlehem",
    "Hebron",
    "Nablus",
    "Jenin",
    "Tulkarm",
    "Qalqilya",
    "Jericho",
    "Khan Yunis",
    "Rafah",
  ],
  Peru: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Iquitos", "Cusco"],
  Philippines: [
    "Manila",
    "Quezon City",
    "Davao City",
    "Cebu City",
    "Zamboanga City",
    "Taguig City",
  ],
  Poland: ["Warsaw", "Krakow", "Wroclaw", "Poznan", "Gdansk", "Szczecin"],
  Qatar: ["Doha", "Al Rayyan", "Umm Salal", "Al Khor", "Al Wakrah", "Mesaieed"],
  Romania: [
    "Bucharest",
    "Cluj-Napoca",
    "Timisoara",
    "Iasi",
    "Craiova",
    "Constanta",
  ],
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Nizhny Novgorod",
    "Kazan",
  ],
  SaudiArabia: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar"],
  SouthAfrica: [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
  ],
  SouthKorea: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga"],
  SriLanka: ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo", "Trincomalee"],
  Sudan: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid", "Nyala"],
  Sweden: ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras", "Orebro"],
  Switzerland: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne"],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Krabi", "Hua Hin"],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana"],
  UAE: ["Dubai", "Abu Dhabi", "Sharjah", "Ras Al Khaimah", "Fujairah", "Ajman"],
  UK: [
    "London",
    "Manchester",
    "Birmingham",
    "Edinburgh",
    "Glasgow",
    "Liverpool",
  ],
  USA: [
    "New York",
    "Los Angeles",
    "Chicago",
    "San Francisco",
    "Miami",
    "Las Vegas",
  ],
  Vietnam: [
    "Hanoi",
    "Ho Chi Minh City",
    "Da Nang",
    "Hue",
    "Nha Trang",
    "Can Tho",
  ],
  Yemen: ["Sana'a", "Aden", "Taiz", "Hodeidah", "Ibb", "Dhamar"],
  Zambia: ["Lusaka", "Ndola", "Kitwe", "Kabwe", "Chingola", "Mufulira"],
  Zimbabwe: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Kwekwe"],
};

export { NameOfCities, NameOfCountries };
